version: "3"

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonar_qabf
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: 
      SONAR_JDBC_PASSWORD: 
    ports:
      - "9000:9000"
    networks:
      - qg_net1
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    container_name: postgres_qabf
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: sonar
    networks:
      - qg_net1
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_qabf
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: sonar
      MB_DB_PORT: 5432
      MB_DB_USER: 
      MB_DB_PASS: 
      MB_DB_HOST: postgres_qg
    networks:
      - qg_net1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:

networks:
  qg_net1:
    driver: bridge
